feat: add generic error widget when caregiver list is empty
savannahghi/mycarehub-frontend pull request #1021
Opened 2023-05-19 13:42 UTC by LUCYOGUTU

2023-05-22 07:55 UTC, LUCYOGUTU commented
![consent](https://github.com/savannahghi/mycarehub-frontend/assets/81163779/f7408da3-7c88-4dad-ab83-9a5f7491d7b4)

2023-05-22 07:57 UTC, byronkimani approved these changes

2023-05-22 10:22 UTC, abiudrn requested changes

2023-05-22 10:22 UTC, abiudrn commented on lib/domain/core/value_objects/app_strings.dart
> +const String noCaregiversString = 'There are no Caregivers found.';
```suggestion
const String noCaregiversString = 'No assigned caregivers';
```

2023-05-22 10:22 UTC, abiudrn commented on lib/domain/core/value_objects/app_strings.dart
> +    'Please try again or contact support';
```suggestion
    'You do not have any assigned caregivers right now. No worries though, we will notify you when you are assigned one';
```

2023-05-22 12:04 UTC, EugeneDevv approved these changes

2023-05-23 04:58 UTC, abiudrn approved these changes

2023-05-23 04:59 UTC, merged