chore: refactor caregiver onboarding flow
savannahghi/mycarehub-frontend pull request #1086
Opened 2023-07-27 13:09 UTC by EugeneDevv

2023-07-31 12:57 UTC, abiudrn requested changes

2023-07-31 12:57 UTC, abiudrn commented on lib/application/redux/actions/caregiver/set_caregiver_current_client_action.dart
> +    store.dispatch(SetPusherAction(client: client));
Something is missing here, a communities login action usually is dispatched somewhere within this logic. Add it in order for the communities feature to work 

See https://github.com/savannahghi/mycarehub-frontend/blob/mycarehub/lib/application/redux/actions/programs/set_current_program_action.dart#L43``

2023-07-31 13:16 UTC, lucyogutu approved these changes

2023-07-31 13:42 UTC, byronkimani approved these changes

2023-08-01 04:14 UTC, abiudrn approved these changes

2023-08-01 04:14 UTC, merged