fix: lastname returning UNKNOWN
savannahghi/mycarehub-frontend pull request #873
Opened 2022-09-23 09:31 UTC by LUCYOGUTU

![WhatsApp Image 2022-09-23 at 12 27 38](https://user-images.githubusercontent.com/81163779/191932157-a1cb08ea-cedb-4838-9589-0c431d0b5b18.jpeg)

2022-09-23 09:35 UTC, byronkimani approved these changes

2022-09-23 09:39 UTC, abiudrn requested changes

2022-09-23 09:39 UTC, abiudrn commented on lib/application/redux/actions/onboarding/phone_login_action.dart
> +          final List<String> names = fullName.trim().split(' ');
This solution fixes half the problem. Find out where the actual last and first names are used and apply defensive programming there.

If the first name is empty, replace it with a `""` and not `UNKNOWN`. The same goes for the last name

2022-09-23 13:54 UTC, abiudrn commented on lib/application/redux/actions/onboarding/phone_login_action.dart
> +          final List<String> names = fullName.trim().split(' ');
Much better.

2022-09-26 06:14 UTC, abiudrn approved these changes

2022-09-26 06:14 UTC, merged