chore: upraded flutter version and dependencies
savannahghi/mycarehub-frontend pull request #919
Opened 2023-01-06 11:34 UTC by LUCYOGUTU

2023-01-12 06:31 UTC, abiudrn requested changes

2023-01-12 06:31 UTC, abiudrn commented on android/.settings/org.eclipse.buildship.core.prefs
> +arguments=--init-script /home/lucyogutu/.config/Code/User/globalStorage/redhat.java/1.13.0/config_linux/org.eclipse.osgi/51/0/.cp/gradle/init/init.gradle --init-script /home/lucyogutu/.config/Code/Us
Revert this change. Consult @EugeneDevv

2023-01-12 06:31 UTC, abiudrn commented on android/app/build.gradle
> +    implementation "androidx.window:window-java:1.0.0-rc01"
What are these libraries used for?

2023-01-12 06:31 UTC, abiudrn commented on lib/application/redux/actions/communities/accept_decline_communities_invite_action.dart
> +    return state;
We should not return `state` if we haven't modified it in this case

2023-01-12 06:31 UTC, abiudrn commented on lib/application/redux/actions/create_health_diary_action.dart
> +          'reportToStaff': '$shouldShareHealthRecord',
`shouldShareHealthRecord` was a bool before, is there a reason it has been changed to a string?

2023-01-12 06:31 UTC, abiudrn commented on lib/application/redux/actions/screening_tools/fetch_screening_questions_action.dart
> +        Sentry.captureException(UserException(errors));
Why has this change been made? The original method did a better job at reporting because it attached all the necessary debugging information

2023-01-12 06:43 UTC, EugeneDevv commented on lib/application/redux/actions/create_health_diary_action.dart
> +          'reportToStaff': '$shouldShareHealthRecord',
There is an assertion that parameter values can only be numbers and strings

2023-01-12 07:22 UTC, EugeneDevv commented on android/app/build.gradle
> +    implementation "androidx.window:window-java:1.0.0-rc01"
This was in a bid to fix the Android runtime errors after the flutter SDK upgrade.  [Desugaring](https://developer.android.com/studio/write/java8-support), which enables lower Android versions to work with newer Java APIs solved the errors was the only solution we found online. The last two libraries were introduced to fix errors caused by desugaring, the [issue](https://github.com/flutter/flutter/issues/110658) is still open in flutter's GitHub repository.

2023-01-12 11:04 UTC, EugeneDevv approved these changes

2023-01-13 06:41 UTC, abiudrn commented on android/app/build.gradle
> +    implementation "androidx.window:window-java:1.0.0-rc01"
Noted

2023-01-13 06:45 UTC, abiudrn approved these changes

2023-01-13 06:45 UTC, merged